apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi-templatemap
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-templatemap
  namespace: kube-system
spec:
  selector:
    matchLabels:
      csi-plugin: templatemap
  template:
    metadata:
      labels:
        csi-plugin: templatemap
    spec:
      containers:
      - name: node-driver-registrar
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -rf /registration/csi-templatemap-reg.sock"]
        args:
          - "--csi-address=unix:///csi/csi.sock"
          - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi-templatemap/csi.sock"
          - "--v=5"
        volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /registration
            name: registration-dir
      - name: csi-templatemap
        image: elemir/templatemap:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        args: ["--nodeid=${KUBE_NODE_ID}"]
        env:
        - name: KUBE_NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /var/lib/kubelet/pods
            name: pods-dir
      volumes:
      - name: pods-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/csi-templatemap
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
