apiVersion: v1
kind: ServiceAccount
metadata: 
  name: test-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-test-accessor
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-test-accessor
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-binding
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-test-accessor
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-binding
subjects:
- kind: ServiceAccount
  name: test-sa
roleRef:
  kind: Role
  name: pod-test-accessor
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  test.html: |
    <html>
    <body>
      Hello world!
    </body>
    </html>
  index.html: |
    <html>
    <body>
      Nothing is real
      {{ .Pod.Name }}
    </body>
    </html>

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.19.2-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: test
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  volumes:
  - name: test
    csi:
      driver: csi-templatemap
      volumeAttributes:
        configMapName: test
        serviceAccountName: test-sa
