apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  test.html: |
    <html>
    <body>
      Hello world!
    </body>
    </html>
  index.html: |
    <html>
    <body>
      Nothing is real
      {{ .Pod.Name }}
    </body>
    </html>

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.19.2-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: test
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  volumes:
  - name: test
    csi:
      driver: csi-templatemap
      volumeAttributes:
        name: test
